"""
Quantise the student to int8 and prove equivalence (design §9.6).

Quantisation bugs are silent and look exactly like "the model doesn't generalise to
hardware". The gate: argmax must agree with fp32 on >=99.5% of validation windows and
the posterior L1 distance must stay under 0.02. Nothing ships otherwise.

Also emits a C header so the same weights compile into the ESP-IDF firmware.
"""
from __future__ import annotations

import argparse, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np


def quantise(W: np.ndarray):
    """Symmetric PER-OUTPUT-CHANNEL int8.

    Per-tensor scaling failed the equivalence gate (99.45% vs the 99.5% required):
    one large-magnitude column forces a coarse scale on every other column. Giving
    each output neuron its own scale is the standard fix and costs only one float
    per column."""
    # Clip at the 99.9th percentile rather than the max: a single outlier weight
    # otherwise inflates the scale for its whole column and costs real accuracy.
    s = np.percentile(np.abs(W), 99.9, axis=0) / 127.0
    s = np.maximum(s, np.max(np.abs(W), axis=0) / 127.0 * 0.25)
    s[s == 0] = 1.0
    q = np.clip(np.round(W / s), -127, 127).astype(np.int8)
    return q, s.astype(np.float32)


def fwd(x, Ws, bs):
    h = x
    for i, (W, b) in enumerate(zip(Ws, bs)):
        h = h @ W + b
        if i < len(Ws) - 1:
            h = np.maximum(h, 0.0)
    e = np.exp(h - h.max())
    return e / e.sum()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", default="../data/student_final/student_bundle.json")
    ap.add_argument("--traces", default="../data/traces_all/val.jsonl")
    ap.add_argument("--out", default="../data/student_final")
    a = ap.parse_args()

    d = json.load(open(a.bundle))
    X = np.array([json.loads(l)["features"] for l in open(a.traces)], dtype=np.float32)
    print(f"equivalence set: {X.shape[0]} validation windows")

    report = {}
    qbundle = {"contract_version": d["contract_version"], "n_features": d["n_features"],
               "cost_order": d["cost_order"], "cost_matrix": d["cost_matrix"],
               "abstain_threshold": d["abstain_threshold"]}
    total_bytes = 0
    for head in ("cause", "call"):
        Ws = [np.asarray(w, np.float32) for w in d[head]["W"]]
        bs = [np.asarray(b, np.float32) for b in d[head]["b"]]
        qW, sc = [], []
        for W in Ws:
            q, s = quantise(W)
            qW.append(q); sc.append(s)
            total_bytes += q.size
        agree = 0; l1 = 0.0
        for x in X:
            p32 = fwd(x, Ws, bs)
            pq = fwd(x, [q.astype(np.float32) * s[None, :] for q, s in zip(qW, sc)], bs)
            agree += int(np.argmax(p32) == np.argmax(pq))
            l1 += float(np.abs(p32 - pq).sum())
        n = len(X)
        report[head] = {"argmax_agreement": agree / n, "mean_l1": l1 / n}
        passes = (agree / n >= 0.995) and (l1 / n < 0.02)
        print(f"  {head:6s}: argmax agreement={agree/n:.4f}  mean posterior L1={l1/n:.5f}"
              f"   {'int8 OK' if passes else 'FAILS GATE -> keeping fp32'}")
        if passes:
            qbundle[head] = {"classes": d[head]["classes"],
                             "W_int8": [q.tolist() for q in qW],
                             "W_scale": [x.tolist() for x in sc],
                             "b": [b.tolist() for b in bs]}
        else:
            # MIXED PRECISION. A head that cannot meet the equivalence gate is not
            # shipped quantised -- we keep it fp32 rather than silently accept a
            # behavioural change. The call head is ~4 K params, so this costs ~15 KB
            # of a 512 KB budget and the bundle still fits 20x over.
            total_bytes += sum(w.size * 3 for w in Ws)   # fp32 is 4 B not 1 B
            qbundle[head] = {"classes": d[head]["classes"],
                             "W": [w.tolist() for w in Ws],
                             "b": [b.tolist() for b in bs]}

    quantised = [h for h in report if "W_int8" in qbundle[h]]
    print(f"\n  equivalence gate: heads shipped int8 = {quantised or 'none'}; "
          f"others kept fp32 (mixed precision)")
    print(f"  int8 weight bytes: {total_bytes:,} ({total_bytes/1024:.1f} KB)")
    print(f"  ESP32 budget 512 KB -> {'FITS' if total_bytes/1024 < 512 else 'TOO BIG'} "
          f"({512/(total_bytes/1024):.0f}x headroom)")

    p = os.path.join(a.out, "student_int8.json")
    json.dump(qbundle, open(p, "w"))
    # C header for the ESP-IDF build
    hp = os.path.join(a.out, "student_weights.h")
    with open(hp, "w") as fh:
        fh.write("/* Auto-generated by train/export_int8.py. Do not edit. */\n")
        fh.write("#ifndef STUDENT_WEIGHTS_H\n#define STUDENT_WEIGHTS_H\n#include <stdint.h>\n\n")
        fh.write(f"#define STUDENT_N_FEATURES {d['n_features']}\n")
        for head in ("cause", "call"):
            for li, q in enumerate(qbundle[head]["W_int8"]):
                arr = np.asarray(q, dtype=np.int8)
                fh.write(f"\n/* {head} layer {li}: {arr.shape[0]}x{arr.shape[1]} */\n")
                sca = qbundle[head]["W_scale"][li]
                fh.write(f"static const float {head}_w{li}_scale[{len(sca)}] = {{")
                fh.write(",".join(f"{v:.9g}f" for v in sca))
                fh.write("};\n")
                fh.write(f"static const int8_t {head}_w{li}[{arr.size}] = {{")
                fh.write(",".join(str(int(v)) for v in arr.flatten()))
                fh.write("};\n")
        fh.write("\n#endif\n")
    print(f"  wrote {p}")
    print(f"  wrote {hp} ({os.path.getsize(hp)/1024:.1f} KB C header for ESP-IDF)")
    json.dump(report, open(os.path.join(a.out, "int8_equivalence.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
